project_id = "xrerhrqxfvvwiefzlkux"

[functions.generate-quote]
verify_jwt = true

[functions.tracking]
verify_jwt = true

[functions.create-order]
verify_jwt = true

[functions.calculate-b2b-pricing]
verify_jwt = true

[functions.check-cpf-cnpj-duplicity]
verify_jwt = false

[functions.send-approval-notification]
verify_jwt = true

[functions.approve-driver]
verify_jwt = true

[functions.approve-b2b-carrier]
verify_jwt = true

[functions.notify-admin-new-registration]
verify_jwt = false

